apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: explorviz
    run: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: explorviz
      run: frontend
  template:
    metadata:
      labels:
        app: explorviz
        run: frontend
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}

 
