apiVersion: apps/v1
kind: Deployment
metadata:
  name: span-service
  labels:
    app: explorviz
    run: span-service
spec:
  replicas: {{ .Values.span.replicaCount }}
  selector:
    matchLabels:
      app: explorviz
      run: span-service
  template:
    metadata:
      labels:
        app: explorviz
        run: span-service
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: wait-for-schema-registry
          image: curlimages/curl:8.7.1
          command:
            - sh
            - -c
            - |
                until curl -sf http://schema-registry:{{ .Values.schemaRegistry.port }}/subjects | grep -q "\["; do
                  echo "Schema Registry not ready yet... sleeping 5s";
                  sleep 5;
                done;
                echo "Schema Registry is ready";

        - name: wait-for-cassandra
          image: "{{ .Values.image.cassandra }}:{{ .Values.image.cassandraTag }}"
          command:
            - sh
            - -c
            - |
                echo "Waiting for Cassandra keyspace 'explorviz'";
                until cqlsh cassandra.default.svc.cluster.local {{ .Values.cassandra.port }} -u cassandra -p cassandra -e "DESCRIBE KEYSPACE explorviz" >/dev/null 2>&1; do
                  echo "Keyspace not ready yet... sleeping 5s";
                  sleep 5;
                done;
                echo "Keyspace 'explorviz' is ready";
      containers:
        - name: span-service
          image: "{{ .Values.image.span }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.span.port }}
              name: http
          env:
            {{- range $key, $value := .Values.span.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}


