apiVersion: v1
kind: Service
metadata:
  name: otel-transformer
  labels:
    app: teastore
    run: otel-transformer
spec:
  type: {{ .Values.service.type}}
  ports:
    - port: {{ .Values.otelTransformer.port }}
      protocol: TCP
  selector:
    app: teastore
    run: otel-transformer
