apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
  labels:
    app: teastore
    run: teastore-persistence
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: teastore
      run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: wait-for-teastore-registry
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for teastore-registry to be ready"
              until nc -z teastore-registry {{ .Values.service.port  }}; do
                echo "Still waiting for teastore-registry on port {{ .Values.service.port  }}"
                sleep 3
              done
              echo "teastore-registry is ready"
      containers:
        - name: teastore-persistence
          image: "{{ .Values.image.persistence }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: HOST_NAME
              value: "teastore-persistence"
            - name: REGISTRY_HOST
              value: "teastore-registry"
            - name: DB_HOST
              value: "teastore-db"
            - name: DB_PORT
              value: "{{ .Values.db.port }}"
            - name: RABBITMQ_HOST
              value: "teastore-rabbitmq"
          volumeMounts:
            - name: kieker-config
              mountPath: /kieker/config/kieker.monitoring.properties
              subPath: kieker.monitoring.properties
              readOnly: false
      volumes:
        - name: kieker-config
          configMap:
            name: kieker-config
