apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: teastore
      run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      initContainers:
        - name: wait-for-otel-transformer
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for otel-transformer to be ready on port 10001"
              until nc -z otel-transformer 10001; do
                echo "otel-transformer not ready yet. sleeping 5s"
                sleep 5
              done
              echo "otel-transformer is ready"
      containers:
        - name: teastore-db
          image: "{{ .Values.image.db }}:{{ .Values.image.tag }}"
          ports:
            - name: mysql
              containerPort: {{ .Values.db.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.db.resources.requests.cpu }}
              memory: {{ .Values.db.resources.requests.memory }}
            limits:
              cpu: {{ .Values.db.resources.limits.cpu }}
              memory: {{ .Values.db.resources.limits.memory }}
