apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-registry
  labels: 
     app: teastore
     run: teastore-registry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      app: teastore
      run: teastore-registry 
  template:
    metadata:
      labels: 
         app: teastore
         run: teastore-registry 
    spec:
      initContainers:
        - name: wait-for-teastore-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z teastore-db 3306; do
                echo "teastore-db not ready yet... sleeping 5s"
                sleep 5
              done
              echo "teastore-db is ready"
      containers:
        - name: teastore-registry
          image: "{{ .Values.image.registry }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
      
